# debug: true

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enable: true
jwt:
  secret: 3292f52f5c6531299ae2e3b110df21653292f52f5c6531299ae2e3b110df2165